FROM mcr.microsoft.com/dotnet/core/sdk:3.0 as build
WORKDIR /code
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /app src/Edelstein.Service.All

FROM mcr.microsoft.com/dotnet/core/runtime:3.0 as runtime
WORKDIR /app
COPY --from=data /app .
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Edelstein.Service.All.dll"]