namespace Edelstein.Service.Game.Fields.Objects.Mob.Stats
{
    public enum MobStatType
    {
        PAD = 0x0,
        PDR = 0x1,
        MAD = 0x2,
        MDR = 0x3,
        ACC = 0x4,
        EVA = 0x5,
        Speed = 0x6,
        Stun = 0x7,
        Freeze = 0x8,
        Poison = 0x9,
        Seal = 0xA,
        Darkness = 0xB,
        PowerUp = 0xC,
        MagicUp = 0xD,
        PGuardUp = 0xE,
        MGuardUp = 0xF,
        Doom = 0x10,
        Web = 0x11,
        PImmune = 0x12,
        MImmune = 0x13,
        Showdown = 0x14,
        HardSkin = 0x15,
        Ambush = 0x16,
        DamagedElemAttr = 0x17,
        Venom = 0x18,
        Blind = 0x19,
        SealSkill = 0x1A,
        Burned = 0x1B,
        Dazzle = 0x1C,
        PCounter = 0x1D,
        MCounter = 0x1E,
        Disable = 0x1F,
        RiseByToss = 0x20,
        BodyPressure = 0x21,
        Weakness = 0x22,
        TimeBomb = 0x23,
        MagicCrash = 0x24,
        HealByDamage = 0x25
    }
}