namespace Edelstein.Core.Entities.Characters
{
    public enum KeyMenu
    {
        Equip = 0x0,
        Item = 0x1,
        Stat = 0x2,
        Skill = 0x3,
        Friend = 0x4,
        WorldMap = 0x5,
        Messenger = 0x6,
        MiniMap = 0x7,
        Quest = 0x8,
        KeyConfig = 0x9,
        ChatAll = 0xA,
        ChatWhisper = 0xB,
        ChatParty = 0xC,
        ChatFriend = 0xD,
        Shortcut = 0xE,
        QuickSlot = 0xF,
        ChatType = 0x10,
        Guild = 0x11,
        ChatGuild = 0x12,
        Party = 0x13,
        QuestAlarm = 0x14,
        ChatCouple = 0x15,
        MonsterBook = 0x16,
        CashShop = 0x17,
        ChatAlliance = 0x18,
        PartySearch = 0x19,
        Family = 0x1A,
        MedalQuest = 0x1B,
        Expedition = 0x1C,
        ChatExpedition = 0x1D,
        Pickup = 0x32,
        Sit = 0x33,
        Attack = 0x34,
        Jump = 0x35,
        NpcTalk = 0x36,
        Emotion0 = 0x64,
        Emotion1 = 0x65,
        Emotion2 = 0x66,
        Emotion3 = 0x67,
        Emotion4 = 0x68,
        Emotion5 = 0x69,
        Emotion6 = 0x6A
    }
}