<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\protocol\Edelstein.Protocol.Utilities\Edelstein.Protocol.Utilities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Repositories\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
  </ItemGroup>
</Project>
