// <auto-generated />
using System;
using Edelstein.Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edelstein.Common.Database.Pgsql.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20240828132429_AddCharacter")]
    partial class AddCharacter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<byte?>("Gender")
                        .HasColumnType("smallint");

                    b.Property<byte>("GradeCode")
                        .HasColumnType("smallint");

                    b.Property<int>("MaplePoint")
                        .HasColumnType("integer");

                    b.Property<int>("NexonCash")
                        .HasColumnType("integer");

                    b.Property<string>("PIN")
                        .HasColumnType("text");

                    b.Property<int>("PrepaidNXCash")
                        .HasColumnType("integer");

                    b.Property<string>("SPW")
                        .HasColumnType("text");

                    b.Property<short>("SubGradeCode")
                        .HasColumnType("smallint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccountWorldData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterSlotMax")
                        .HasColumnType("integer");

                    b.Property<string>("Locker")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{\"SlotMax\":999,\"Items\":[]}");

                    b.Property<string>("Trunk")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{\"Money\":0,\"SlotMax\":4,\"Items\":[]}");

                    b.Property<int>("WorldID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("account_world_data", (string)null);
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbCharacter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<short>("AP")
                        .HasColumnType("smallint");

                    b.Property<int>("AccountWorldDataID")
                        .HasColumnType("integer");

                    b.Property<short>("DEX")
                        .HasColumnType("smallint");

                    b.Property<int>("EXP")
                        .HasColumnType("integer");

                    b.Property<int>("Face")
                        .HasColumnType("integer");

                    b.Property<int>("FieldID")
                        .HasColumnType("integer");

                    b.Property<byte>("FieldPortal")
                        .HasColumnType("smallint");

                    b.Property<byte>("Gender")
                        .HasColumnType("smallint");

                    b.Property<int>("HP")
                        .HasColumnType("integer");

                    b.Property<int>("Hair")
                        .HasColumnType("integer");

                    b.Property<short>("INT")
                        .HasColumnType("smallint");

                    b.Property<short>("Job")
                        .HasColumnType("smallint");

                    b.Property<short>("LUK")
                        .HasColumnType("smallint");

                    b.Property<byte>("Level")
                        .HasColumnType("smallint");

                    b.Property<int>("MP")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMP")
                        .HasColumnType("integer");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("POP")
                        .HasColumnType("smallint");

                    b.Property<int>("PlayTime")
                        .HasColumnType("integer");

                    b.Property<short>("SP")
                        .HasColumnType("smallint");

                    b.Property<short>("STR")
                        .HasColumnType("smallint");

                    b.Property<byte>("Skin")
                        .HasColumnType("smallint");

                    b.Property<short>("SubJob")
                        .HasColumnType("smallint");

                    b.Property<int>("TempEXP")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AccountWorldDataID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Auth.DbIdentity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("identities", (string)null);
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Migration.DbMigrationInfo", b =>
                {
                    b.Property<int>("AccountID")
                        .HasColumnType("integer");

                    b.Property<int>("AccountWorldDataID")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateExpire")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromServerID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToServerID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountID", "AccountWorldDataID", "CharacterID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.HasIndex("AccountWorldDataID")
                        .IsUnique();

                    b.HasIndex("CharacterID")
                        .IsUnique();

                    b.HasIndex("FromServerID");

                    b.HasIndex("ToServerID");

                    b.ToTable("migration_info", (string)null);
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Server.DbServerInfo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateExpire")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<long>("Secret")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("server_info", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Server");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Session.DbSessionInfo", b =>
                {
                    b.Property<int>("ActiveAccount")
                        .HasColumnType("integer");

                    b.Property<int?>("ActiveCharacter")
                        .HasColumnType("integer");

                    b.Property<long>("Secret")
                        .HasColumnType("bigint");

                    b.Property<string>("ServerID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ActiveAccount");

                    b.HasIndex("ActiveCharacter")
                        .IsUnique();

                    b.HasIndex("ServerID");

                    b.ToTable("session_info", (string)null);
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Server.DbServerInfoGame", b =>
                {
                    b.HasBaseType("Edelstein.Common.Database.Entities.Services.Server.DbServerInfo");

                    b.Property<int>("ChannelID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdultChannel")
                        .HasColumnType("boolean");

                    b.Property<int>("WorldID")
                        .HasColumnType("integer");

                    b.ToTable("server_info", (string)null);

                    b.HasDiscriminator().HasValue("Game");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Server.DbServerInfoLogin", b =>
                {
                    b.HasBaseType("Edelstein.Common.Database.Entities.Services.Server.DbServerInfo");

                    b.ToTable("server_info", (string)null);

                    b.HasDiscriminator().HasValue("Login");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccountWorldData", b =>
                {
                    b.HasOne("Edelstein.Common.Database.Entities.DbAccount", "Account")
                        .WithMany("AccountWorldData")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbCharacter", b =>
                {
                    b.HasOne("Edelstein.Common.Database.Entities.DbAccountWorldData", "AccountWorldData")
                        .WithMany("Characters")
                        .HasForeignKey("AccountWorldDataID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountWorldData");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Migration.DbMigrationInfo", b =>
                {
                    b.HasOne("Edelstein.Common.Database.Entities.Services.Session.DbSessionInfo", "Session")
                        .WithOne("Migration")
                        .HasForeignKey("Edelstein.Common.Database.Entities.Services.Migration.DbMigrationInfo", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edelstein.Common.Database.Entities.DbAccount", "Account")
                        .WithOne("Migration")
                        .HasForeignKey("Edelstein.Common.Database.Entities.Services.Migration.DbMigrationInfo", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edelstein.Common.Database.Entities.DbAccountWorldData", "AccountWorldData")
                        .WithOne("Migration")
                        .HasForeignKey("Edelstein.Common.Database.Entities.Services.Migration.DbMigrationInfo", "AccountWorldDataID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edelstein.Common.Database.Entities.DbCharacter", "Character")
                        .WithOne("Migration")
                        .HasForeignKey("Edelstein.Common.Database.Entities.Services.Migration.DbMigrationInfo", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edelstein.Common.Database.Entities.Services.Server.DbServerInfo", "FromServer")
                        .WithMany("MigrationOut")
                        .HasForeignKey("FromServerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edelstein.Common.Database.Entities.Services.Server.DbServerInfo", "ToServer")
                        .WithMany("MigrationIn")
                        .HasForeignKey("ToServerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("AccountWorldData");

                    b.Navigation("Character");

                    b.Navigation("FromServer");

                    b.Navigation("Session");

                    b.Navigation("ToServer");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Session.DbSessionInfo", b =>
                {
                    b.HasOne("Edelstein.Common.Database.Entities.DbAccount", "Account")
                        .WithOne("Session")
                        .HasForeignKey("Edelstein.Common.Database.Entities.Services.Session.DbSessionInfo", "ActiveAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edelstein.Common.Database.Entities.DbCharacter", "Character")
                        .WithOne("Session")
                        .HasForeignKey("Edelstein.Common.Database.Entities.Services.Session.DbSessionInfo", "ActiveCharacter")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Edelstein.Common.Database.Entities.Services.Server.DbServerInfo", "Server")
                        .WithMany("Sessions")
                        .HasForeignKey("ServerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Character");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccount", b =>
                {
                    b.Navigation("AccountWorldData");

                    b.Navigation("Migration");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccountWorldData", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Migration");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbCharacter", b =>
                {
                    b.Navigation("Migration");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Server.DbServerInfo", b =>
                {
                    b.Navigation("MigrationIn");

                    b.Navigation("MigrationOut");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Session.DbSessionInfo", b =>
                {
                    b.Navigation("Migration");
                });
#pragma warning restore 612, 618
        }
    }
}
