namespace Edelstein.Core.Gameplay
{
    public enum BodyPart : short
    {
        Hair = 0,
        Cap = 1,
        FaceAcc = 2,
        EyeAcc = 3,
        EarAcc = 4,
        Clothes = 5,
        Pants = 6,
        Shoes = 7,
        Gloves = 8,
        Cape = 9,
        Shield = 10,
        Weapon = 11,

        Ring1 = 12,
        Ring2 = 13,

        PetWear = 14,

        Ring3 = 15,
        Ring4 = 16,
        Pendant = 17,

        TamingMob = 18,
        Saddle = 19,
        MobEquip = 20,

        PetRingLabel = 21,
        PetAbilItem = 22,
        PetAbilMeso = 23,
        PetAbilHpConsume = 24,
        PetAbilMechanicConsume = 25,
        PetAbilSweepForDrop = 26,
        PetAbilLongRange = 27,
        PetAbilPickupOthers = 28,
        PetRingQuote = 29,
        PetWear2 = 30,
        PetRingLabel2 = 31,
        PetRingQuote2 = 32,
        PetAbilItem2 = 33,
        PetAbilMeso2 = 34,
        PetAbilSweepForDrop2 = 35,
        PetAbilLongRange2 = 36,
        PetAbilPickupOthers2 = 37,
        PetWear3 = 38,
        PetRingLabel3 = 39,
        PetRingQuote3 = 40,
        PetAbilItem3 = 41,
        PetAbilMeso3 = 42,
        PetAbilSweepForDrop3 = 43,
        PetAbilLongRange3 = 44,
        PetAbilPickupOthers3 = 45,
        PetAbilIgnoreItems1 = 46,
        PetAbilIgnoreItems2 = 47,
        PetAbilIgnoreItems3 = 48,

        Medal = 49,
        Belt = 50,
        Shoulder = 51,
        Nothing3 = 54,
        Nothing2 = 55,
        Nothing1 = 56,
        Nothing0 = 57,

        Ext0 = 59,
        ExtPendant1 = 59,
        Ext1 = 60,
        Ext2 = 61,
        Ext3 = 62,
        Ext4 = 63,
        Ext5 = 64,
        Ext6 = 65,

        Sticker = 100,

        DragonBase = 1000,
        DragonCap = 1000,
        DragonPendant = 1001,
        DragonWing = 1002,
        DragonShoes = 1003,

        MechanicBase = 1100,
        MechanicEngine = 1100,
        MechanicArm = 1101,
        MechanicLeg = 1102,
        MechanicFrame = 1103,
        MechanicTransistor = 1104,
    }
}