<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Edelstein.Protocol.Utilities\Edelstein.Protocol.Utilities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="protobuf-net.Grpc" />
    <PackageReference Include="System.ServiceModel.Primitives" />
  </ItemGroup>
</Project>
