namespace Edelstein.Common.Gameplay.Shop.Types;

public enum ShopRequestOperations
{
    WebShopOrderGetList = 0x0,
    LoadLocker = 0x1,
    LoadWish = 0x2,
    Buy = 0x3,
    Gift = 0x4,
    SetWish = 0x5,
    IncSlotCount = 0x6,
    IncTrunkCount = 0x7,
    IncCharSlotCount = 0x8,
    IncBuyCharCount = 0x9,
    EnableEquipSlotExt = 0xA,
    CancelPurchase = 0xB,
    ConfirmPurchase = 0xC,
    Destroy = 0xD,
    MoveLtoS = 0xE,
    MoveStoL = 0xF,
    Expire = 0x10,
    Use = 0x11,
    StatChange = 0x12,
    SkillChange = 0x13,
    SkillReset = 0x14,
    DestroyPetItem = 0x15,
    SetPetName = 0x16,
    SetPetLife = 0x17,
    SetPetSkill = 0x18,
    SetItemName = 0x19,
    SendMemo = 0x1A,
    GetMaplePoint = 0x1B,
    Rebate = 0x1C,
    UseCoupon = 0x1D,
    GiftCoupon = 0x1E,
    Couple = 0x1F,
    BuyPackage = 0x20,
    GiftPackage = 0x21,
    BuyNormal = 0x22,
    ApplyWishListEvent = 0x23,
    MovePetStat = 0x24,
    FriendShip = 0x25,
    ShopScan = 0x26,
    LoadPetExceptionList = 0x27,
    UpdatePetExceptionList = 0x28,
    FreeCashItem = 0x29,
    LoadFreeCashItem = 0x2A,
    Script = 0x2B,
    PurchaseRecord = 0x2C,
    TradeDone = 0x2D,
    BuyDone = 0x2E,
    TradeSave = 0x2F,
    TradeLog = 0x30,
    EvolPet = 0x31,
    BuyNameChange = 0x32,
    CancelChangeName = 0x33,
    BuyTransferWorld = 0x35,
    CancelTransferWorld = 0x36,

    CharacterSale = 0x37,

    ItemUpgrade = 0x3C,
    ItemUpgradeFail = 0x3E,
    ItemUpgradeReq = 0x3F,
    ItemUpgradeDone = 0x40,

    Vega = 0x43,

    CashItemGachapon = 0x4A,
    CashGachaponOpen = 0x4B,
    CashGachaponCopy = 0x4C,
    ChangeMaplePoint = 0x4D,

    CheckFreeCashItemTable = 0x4E,

    SetFreeCashItemTable = 0x51,
    
    Give = 0xBD
}
