using System;
using System.Collections.Generic;
using Edelstein.Network.Packets;

namespace Edelstein.Service.Game.Fields.Objects.User.Stats
{
    internal static class TemporaryStatOrder
    {
        internal static readonly TemporaryStatType[] EncodingOrderLocal =
        {
            TemporaryStatType.PAD,
            TemporaryStatType.PDD,
            TemporaryStatType.MAD,
            TemporaryStatType.MDD,
            TemporaryStatType.ACC,
            TemporaryStatType.EVA,
            TemporaryStatType.Craft,
            TemporaryStatType.Speed,
            TemporaryStatType.Jump,
            TemporaryStatType.EMHP,
            TemporaryStatType.EMMP,
            TemporaryStatType.EPAD,
            TemporaryStatType.EPDD,
            TemporaryStatType.EMDD,
            TemporaryStatType.MagicGuard,
            TemporaryStatType.DarkSight,
            TemporaryStatType.Booster,
            TemporaryStatType.PowerGuard,
            TemporaryStatType.Guard,
            TemporaryStatType.SafetyDamage,
            TemporaryStatType.SafetyAbsorb,
            TemporaryStatType.MaxHP,
            TemporaryStatType.MaxMP,
            TemporaryStatType.Invincible,
            TemporaryStatType.SoulArrow,
            TemporaryStatType.Stun,
            TemporaryStatType.Poison,
            TemporaryStatType.Seal,
            TemporaryStatType.Darkness,
            TemporaryStatType.ComboCounter,
            TemporaryStatType.WeaponCharge,
            TemporaryStatType.DragonBlood,
            TemporaryStatType.HolySymbol,
            TemporaryStatType.MesoUp,
            TemporaryStatType.ShadowPartner,
            TemporaryStatType.PickPocket,
            TemporaryStatType.MesoGuard,
            TemporaryStatType.Thaw,
            TemporaryStatType.Weakness,
            TemporaryStatType.Curse,
            TemporaryStatType.Slow,
            TemporaryStatType.Morph,
            TemporaryStatType.Ghost,
            TemporaryStatType.Regen,
            TemporaryStatType.BasicStatUp,
            TemporaryStatType.Stance,
            TemporaryStatType.SharpEyes,
            TemporaryStatType.ManaReflection,
            TemporaryStatType.Attract,
            TemporaryStatType.SpiritJavelin,
            TemporaryStatType.Infinity,
            TemporaryStatType.Holyshield,
            TemporaryStatType.HamString,
            TemporaryStatType.Blind,
            TemporaryStatType.Concentration,
            TemporaryStatType.BanMap,
            TemporaryStatType.MaxLevelBuff,
            TemporaryStatType.Barrier,
            TemporaryStatType.DojangShield,
            TemporaryStatType.ReverseInput,
            TemporaryStatType.MesoUpByItem,
            TemporaryStatType.ItemUpByItem,
            TemporaryStatType.RespectPImmune,
            TemporaryStatType.RespectMImmune,
            TemporaryStatType.DefenseAtt,
            TemporaryStatType.DefenseState,
            TemporaryStatType.DojangBerserk,
            TemporaryStatType.DojangInvincible,
            TemporaryStatType.Spark,
            TemporaryStatType.SoulMasterFinal,
            TemporaryStatType.WindBreakerFinal,
            TemporaryStatType.ElementalReset,
            TemporaryStatType.WindWalk,
            TemporaryStatType.EventRate,
            TemporaryStatType.ComboAbilityBuff,
            TemporaryStatType.ComboDrain,
            TemporaryStatType.ComboBarrier,
            TemporaryStatType.BodyPressure,
            TemporaryStatType.SmartKnockback,
            TemporaryStatType.RepeatEffect,
            TemporaryStatType.ExpBuffRate,
            TemporaryStatType.IncEffectHPPotion,
            TemporaryStatType.IncEffectMPPotion,
            TemporaryStatType.StopPortion,
            TemporaryStatType.StopMotion,
            TemporaryStatType.Fear,
            TemporaryStatType.EvanSlow,
            TemporaryStatType.MagicShield,
            TemporaryStatType.MagicResistance,
            TemporaryStatType.SoulStone,
            TemporaryStatType.Flying,
            TemporaryStatType.Frozen,
            TemporaryStatType.AssistCharge,
            TemporaryStatType.Enrage,
            TemporaryStatType.SuddenDeath,
            TemporaryStatType.NotDamaged,
            TemporaryStatType.FinalCut,
            TemporaryStatType.ThornsEffect,
            TemporaryStatType.SwallowAttackDamage,
            TemporaryStatType.MorewildDamageUp,
            TemporaryStatType.Mine,
            TemporaryStatType.Cyclone,
            TemporaryStatType.SwallowCritical,
            TemporaryStatType.SwallowMaxMP,
            TemporaryStatType.SwallowDefence,
            TemporaryStatType.SwallowEvasion,
            TemporaryStatType.Conversion,
            TemporaryStatType.Revive,
            TemporaryStatType.Sneak,
            TemporaryStatType.Mechanic,
            TemporaryStatType.Aura,
            TemporaryStatType.DarkAura,
            TemporaryStatType.BlueAura,
            TemporaryStatType.YellowAura,
            TemporaryStatType.SuperBody,
            TemporaryStatType.MorewildMaxHP,
            TemporaryStatType.Dice,
            TemporaryStatType.BlessingArmor,
            TemporaryStatType.DamR,
            TemporaryStatType.TeleportMasteryOn,
            TemporaryStatType.CombatOrders,
            TemporaryStatType.Beholder,
            TemporaryStatType.SummonBomb
        };


        internal static readonly IDictionary<TemporaryStatType, Action<TemporaryStat, IPacket>> EncodingOrderRemote =
            new Dictionary<TemporaryStatType, Action<TemporaryStat, IPacket>>
            {
                {TemporaryStatType.Speed, (ts, p) => p.Encode<byte>((byte) ts.Option)},
                {TemporaryStatType.ComboCounter, (ts, p) => p.Encode<byte>((byte) ts.Option)},
                {TemporaryStatType.WeaponCharge, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.Stun, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.Darkness, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.Seal, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.Weakness, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.Curse, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {
                    TemporaryStatType.Poison, (ts, p) =>
                    {
                        p.Encode<short>((short) ts.Option);
                        p.Encode<int>(ts.TemplateID);
                    }
                },
                {TemporaryStatType.ShadowPartner, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.Morph, (ts, p) => p.Encode<short>((short) ts.Option)},
                {TemporaryStatType.Ghost, (ts, p) => p.Encode<short>((short) ts.Option)},
                {TemporaryStatType.Attract, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.SpiritJavelin, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.BanMap, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.Barrier, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.DojangShield, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.ReverseInput, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.RespectPImmune, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.RespectMImmune, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.DefenseAtt, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.DefenseState, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.RepeatEffect, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.StopPortion, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.StopMotion, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.Fear, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.MagicShield, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.Frozen, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.SuddenDeath, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.FinalCut, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.Cyclone, (ts, p) => p.Encode<byte>((byte) ts.Option)},
                {TemporaryStatType.Mechanic, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.DarkAura, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.BlueAura, (ts, p) => p.Encode<int>(ts.TemplateID)},
                {TemporaryStatType.YellowAura, (ts, p) => p.Encode<int>(ts.TemplateID)}
            };

        internal static readonly TemporaryStatType[] EncodingTwoStateOrderRemote =
        {
            TemporaryStatType.EnergyCharged,
            TemporaryStatType.Dash_Speed,
            TemporaryStatType.Dash_Jump,
            TemporaryStatType.RideVehicle,
            TemporaryStatType.PartyBooster,
            TemporaryStatType.GuidedBullet,
            TemporaryStatType.Undead
        };
    }
}