namespace Edelstein.Database.Entities.Characters
{
    public enum KeyMenu
    {
        Equip = 0,
        Item = 1,
        Stat = 2,
        Skill = 3,
        Friend = 4,
        WorldMap = 5,
        Messenger = 6,
        MiniMap = 7,
        Quest = 8,
        KeyConfig = 9,
        ChatAll = 10,
        ChatWhisper = 11,
        ChatParty = 12,
        ChatFriend = 13,
        Shortcut = 14,
        QuickSlot = 15,
        ChatType = 16,
        Guild = 17,
        ChatGuild = 18,
        Party = 19,
        QuestAlarm = 20,
        ChatCouple = 21,
        MonsterBook = 22,
        CashShop = 23,
        ChatAlliance = 24,
        PartySearch = 25,
        Family = 26,
        MedalQuest = 27,
        Expedition = 28,
        ChatExpedition = 29,
        Pickup = 50,
        Sit = 51,
        Attack = 52,
        Jump = 53,
        NpcTalk = 54,
        Emotion0 = 100,
        Emotion1 = 101,
        Emotion2 = 102,
        Emotion3 = 103,
        Emotion4 = 104,
        Emotion5 = 105,
        Emotion6 = 106
    }
}