namespace Edelstein.Plugin.Rue.ClientAnalysis;

public static partial class V95ClientStructs
{
    /// <summary>CWvsContext struct (sizeof=0x4258, singleton at 0x00C64068)</summary>
    public static readonly Dictionary<int, string> CWvsContext = new()
    {
        [Offsets.CWvsContext.FirstUserLoad] = "CWvsContext.m_bFirstUserLoad",
        [Offsets.CWvsContext.AvatarMegaphone] = "CWvsContext.m_bAvatarMegaphone",
        [Offsets.CWvsContext.AmLastUpdate] = "CWvsContext.m_tAM_LastUpdate",
        [Offsets.CWvsContext.TargetPositionX] = "CWvsContext.m_nTargetPosition_X",
        [Offsets.CWvsContext.TargetPositionY] = "CWvsContext.m_nTargetPosition_Y",
        [Offsets.CWvsContext.ChaseEnable] = "CWvsContext.m_bChaseEnable",
        [Offsets.CWvsContext.PetHelpPopUpShown] = "CWvsContext.m_bPetHelpPopUpShown",
        [Offsets.CWvsContext.Cookie] = "CWvsContext.m_Cookie",
        [Offsets.CWvsContext.CookieValid] = "CWvsContext.m_bIsCookieValid",
        [Offsets.CWvsContext.CookieLoadedByArgString] = "CWvsContext.m_bCookieLoadedByArgString",
        [Offsets.CWvsContext.LoginBaseStep] = "CWvsContext.m_nLoginBaseStep",
        [Offsets.CWvsContext.AccountId] = "CWvsContext.m_dwAccountId",
        [Offsets.CWvsContext.Gender] = "CWvsContext.m_nGender",
        [Offsets.CWvsContext.GradeCode] = "CWvsContext.m_nGradeCode",
        [Offsets.CWvsContext.SubGradeCode] = "CWvsContext.m_nSubGradeCode",
        [Offsets.CWvsContext.EmailAccount] = "CWvsContext.m_sEMailAccount",
        [Offsets.CWvsContext.NexonClubId] = "CWvsContext.m_sNexonClubID",
        [Offsets.CWvsContext.CountryId] = "CWvsContext.m_nCountryID",
        [Offsets.CWvsContext.PurchaseExp] = "CWvsContext.m_nPurchaseExp",
        [Offsets.CWvsContext.WorldId] = "CWvsContext.m_nWorldID",
        [Offsets.CWvsContext.ChannelId] = "CWvsContext.m_nChannelID",
        [Offsets.CWvsContext.Premium] = "CWvsContext.m_bPremium",
        [Offsets.CWvsContext.PremiumArgument] = "CWvsContext.m_ulPremiumArgument",
        [Offsets.CWvsContext.ChatBlockReason] = "CWvsContext.m_nChatBlockReason",
        [Offsets.CWvsContext.ChatUnblockDate] = "CWvsContext.m_dtChatUnblockDate",
        [Offsets.CWvsContext.RegisterDate] = "CWvsContext.m_dtRegisterDate",
        [Offsets.CWvsContext.NumOfCharacter] = "CWvsContext.m_nNumOfCharacter",
        [Offsets.CWvsContext.ThisAccountJustCreatedCharacter] = "CWvsContext.m_bThisAccountJustCreatedCharacter",
        [Offsets.CWvsContext.IsGuestAccount] = "CWvsContext.m_bIsGuestAccount",
        [Offsets.CWvsContext.ManagerAccount] = "CWvsContext.m_bManagerAccount",
        [Offsets.CWvsContext.CharacterCount] = "CWvsContext.m_nCharacterCount",
        [Offsets.CWvsContext.SlotCount] = "CWvsContext.m_nSlotCount",
        [Offsets.CWvsContext.ClientKey] = "CWvsContext.m_aClientKey",
        [Offsets.CWvsContext.TesterAccount] = "CWvsContext.m_bTesterAccount",
        [Offsets.CWvsContext.CharacterId] = "CWvsContext.m_dwCharacterId",
        [Offsets.CWvsContext.ExclRequestSent] = "CWvsContext.m_bExclRequestSent",
        [Offsets.CWvsContext.ExclRequestSentTime] = "CWvsContext.m_tExclRequestSent",
        [Offsets.CWvsContext.ExclRequestSentQ] = "CWvsContext.m_tExclRequestSentQ",
        [Offsets.CWvsContext.CharacterData] = "CWvsContext.m_pCharacterData",
        [Offsets.CWvsContext.BasicStat] = "CWvsContext.m_basicStat",
        [Offsets.CWvsContext.SecondaryStat] = "CWvsContext.m_secondaryStat",
        [Offsets.CWvsContext.ForcedStat] = "CWvsContext.m_forcedStat",
        [Offsets.CWvsContext.TemporaryStatView] = "CWvsContext.m_temporaryStatView",
        [Offsets.CWvsContext.TownPortal] = "CWvsContext.m_townPortal",
        [Offsets.CWvsContext.ActiveEffectItemId] = "CWvsContext.m_nActiveEffectItemID",
        [Offsets.CWvsContext.PartyId] = "CWvsContext.m_nPartyID",
        [Offsets.CWvsContext.Party] = "CWvsContext.m_party",
        [Offsets.CWvsContext.FriendArray] = "CWvsContext.m_pFriendArray",
        [Offsets.CWvsContext.MarriedPartnerCurFieldId] = "CWvsContext.m_dwMarriedPartnerCurFieldID",
        [Offsets.CWvsContext.MarriedPartnerId] = "CWvsContext.m_nMarriedPartnerID",
        [Offsets.CWvsContext.PartySearchSetting] = "CWvsContext.m_PartySearch_Setting",
        [Offsets.CWvsContext.PartySearchState] = "CWvsContext.m_nPartySearch_State",
        [Offsets.CWvsContext.KeepPartySearch] = "CWvsContext.m_bKeep_PartySearch",
        [Offsets.CWvsContext.Guild] = "CWvsContext.m_guild",
        [Offsets.CWvsContext.DirectionMode] = "CWvsContext.m_bDirectionMode",
        [Offsets.CWvsContext.StandAloneMode] = "CWvsContext.m_bStandAloneMode",
        [Offsets.CWvsContext.ShowUi] = "CWvsContext.m_bShowUI",
        [Offsets.CWvsContext.ChannelName] = "CWvsContext.m_aChannelName",
        [Offsets.CWvsContext.AdultChannel] = "CWvsContext.m_aAdultChannel",
        [Offsets.CWvsContext.ScreenWidth] = "CWvsContext.m_nScreenWidth",
        [Offsets.CWvsContext.ScreenHeight] = "CWvsContext.m_nScreenHeight",
    };
}
