namespace Edelstein.Plugin.Rue.ClientAnalysis;

public static partial class V95ClientStructs
{
    /// <summary>CLogin struct (sizeof=0x2C8, base=CMapLoadable)</summary>
    public static readonly Dictionary<int, string> CLogin = new()
    {
        [Offsets.CLogin.ConnectionDlg] = "CLogin.m_pConnectionDlg",
        [Offsets.CLogin.IsWaitingVac] = "CLogin.m_bIsWaitingVAC",
        [Offsets.CLogin.IsVacDlgOn] = "CLogin.m_bIsVACDlgOn",
        [Offsets.CLogin.SentTimeVacPacket] = "CLogin.m_tSentTimeVACPacket",
        [Offsets.CLogin.CountRelatedSvrs] = "CLogin.m_nCountRelatedSvrs",
        [Offsets.CLogin.CountCharacters] = "CLogin.m_nCountCharacters",
        [Offsets.CLogin.CountDataReceivedCharacters] = "CLogin.m_nCountDataReceivedCharacters",
        [Offsets.CLogin.RecommendWorld] = "CLogin.m_bRecommandWorld",
        [Offsets.CLogin.AvatarDataVac] = "CLogin.m_aAvatarDataVAC",
        [Offsets.CLogin.RankVac] = "CLogin.m_aRankVAC",
        [Offsets.CLogin.CharacterId] = "CLogin.m_adwCharacterID",
        [Offsets.CLogin.CharacterName] = "CLogin.m_asCharacterName",
        [Offsets.CLogin.WorldId] = "CLogin.m_anWorldID",
        [Offsets.CLogin.LockAvatar] = "CLogin.m_lock_Avatar",
        [Offsets.CLogin.LockCountSvr] = "CLogin.m_lock_CountSvr",
        [Offsets.CLogin.LockCharacter] = "CLogin.m_lock_Character",
        [Offsets.CLogin.LayerBook] = "CLogin.m_pLayerBook",
        [Offsets.CLogin.FadeOutLoginStep] = "CLogin.m_nFadeOutLoginStep",
        [Offsets.CLogin.StartFadeOut] = "CLogin.m_tStartFadeOut",
        [Offsets.CLogin.LoginStep] = "CLogin.m_nLoginStep",
        [Offsets.CLogin.StepChanging] = "CLogin.m_tStepChanging",
        [Offsets.CLogin.RequestSent] = "CLogin.m_bRequestSent",
        [Offsets.CLogin.LoginOpt] = "CLogin.m_bLoginOpt",
        [Offsets.CLogin.QuerySsnOnCreateNewCharacter] = "CLogin.m_bQuerySSNOnCreateNewCharacter",
        [Offsets.CLogin.SlotCount] = "CLogin.m_nSlotCount",
        [Offsets.CLogin.BuyCharCount] = "CLogin.m_nBuyCharCount",
        [Offsets.CLogin.BaseStep] = "CLogin.m_nBaseStep",
        [Offsets.CLogin.Terminate] = "CLogin.m_bTerminate",
        [Offsets.CLogin.FocusedUi] = "CLogin.m_pFocusedUI",
        [Offsets.CLogin.WorldItem] = "CLogin.m_WorldItem",
        [Offsets.CLogin.CharSelected] = "CLogin.m_nCharSelected",
        [Offsets.CLogin.AvatarData] = "CLogin.m_aAvatarData",
        [Offsets.CLogin.Rank] = "CLogin.m_aRank",
        [Offsets.CLogin.OnFamily] = "CLogin.m_abOnFamily",
        [Offsets.CLogin.NewEquip] = "CLogin.m_lNewEquip",
        [Offsets.CLogin.RegStatId] = "CLogin.m_nRegStatID",
        [Offsets.CLogin.LayerLight] = "CLogin.m_pLayerLight",
        [Offsets.CLogin.LayerDust] = "CLogin.m_pLayerDust",
        [Offsets.CLogin.NewAvatar] = "CLogin.m_pNewAvatar",
        [Offsets.CLogin.LoginStart] = "CLogin.m_pLoginStart",
        [Offsets.CLogin.LoginDesc0] = "CLogin.m_pLoginDesc0",
        [Offsets.CLogin.LoginDesc1] = "CLogin.m_pLoginDesc1",
        [Offsets.CLogin.ChildModal] = "CLogin.m_pChildModal",
        [Offsets.CLogin.EventCharacterId] = "CLogin.m_sEventCharacterID",
        [Offsets.CLogin.BalloonCount] = "CLogin.m_nBalloonCount",
        [Offsets.CLogin.Balloon] = "CLogin.m_aBalloon",
        [Offsets.CLogin.LatestConnectedWorldId] = "CLogin.m_nLatestConnectedWorldID",
        [Offsets.CLogin.RecommendWorldMsgLoaded] = "CLogin.m_bRecommendWorldMsgLoaded",
        [Offsets.CLogin.RecommendWorldMsg] = "CLogin.m_aRecommendWorldMsg",
        [Offsets.CLogin.CurSelectedRace] = "CLogin.m_nCurSelectedRace",
        [Offsets.CLogin.CurSelectedSubJob] = "CLogin.m_nCurSelectedSubJob",
        [Offsets.CLogin.Cmd] = "CLogin.m_aCmd",
        [Offsets.CLogin.FadeInRemain] = "CLogin.m_tFadeInRemain",
        [Offsets.CLogin.NeedAgreement] = "CLogin.m_bNeedAgreement",
        [Offsets.CLogin.Gender] = "CLogin.m_nGender",
        [Offsets.CLogin.SubStep] = "CLogin.m_nSubStep",
        [Offsets.CLogin.SubStepChanged] = "CLogin.m_bSubStepChanged",
        [Offsets.CLogin.CheckedName] = "CLogin.m_sCheckedName",
        [Offsets.CLogin.MaleItem] = "CLogin.m_aMaleItem",
        [Offsets.CLogin.FemaleItem] = "CLogin.m_aFemaleItem",
        [Offsets.CLogin.CharSale] = "CLogin.m_bCharSale",
        [Offsets.CLogin.CharSaleJob] = "CLogin.m_nCharSaleJob",
        [Offsets.CLogin.CanHaveExtraChar] = "CLogin.m_bCanHaveExtraChar",
    };
}
