// <auto-generated />
using Edelstein.Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Edelstein.Common.Database.Sqlite.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20240818084527_AddAccountWorldData")]
    partial class AddAccountWorldData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4");

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("GradeCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaplePoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NexonCash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PIN")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrepaidNXCash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SPW")
                        .HasColumnType("TEXT");

                    b.Property<short>("SubGradeCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccountWorldData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterSlotMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Locker")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{\"SlotMax\":999,\"Items\":[]}");

                    b.Property<string>("Trunk")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{\"Money\":0,\"SlotMax\":4,\"Items\":[]}");

                    b.Property<int>("WorldID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("account_world_data", (string)null);
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccountWorldData", b =>
                {
                    b.HasOne("Edelstein.Common.Database.Entities.DbAccount", "Account")
                        .WithMany("AccountWorldData")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccount", b =>
                {
                    b.Navigation("AccountWorldData");
                });
#pragma warning restore 612, 618
        }
    }
}
