// <auto-generated />
using Edelstein.Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Edelstein.Common.Database.Sqlite.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20240818054154_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3");

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("GradeCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaplePoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NexonCash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PIN")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrepaidNXCash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SPW")
                        .HasColumnType("TEXT");

                    b.Property<short>("SubGradeCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
