// <auto-generated />
using System;
using Edelstein.Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Edelstein.Common.Database.Sqlite.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4");

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("GradeCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaplePoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NexonCash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PIN")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrepaidNXCash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SPW")
                        .HasColumnType("TEXT");

                    b.Property<short>("SubGradeCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccountWorldData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterSlotMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Locker")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{\"SlotMax\":999,\"Items\":[]}");

                    b.Property<string>("Trunk")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{\"Money\":0,\"SlotMax\":4,\"Items\":[]}");

                    b.Property<int>("WorldID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("account_world_data", (string)null);
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Auth.DbIdentity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("identities", (string)null);
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Server.DbServerInfo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateExpire")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Secret")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("server_info", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Server");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Session.DbSessionInfo", b =>
                {
                    b.Property<int>("ActiveAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveCharacter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActiveAccount");

                    b.HasIndex("ServerID");

                    b.ToTable("session_info", (string)null);
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Server.DbServerInfoLogin", b =>
                {
                    b.HasBaseType("Edelstein.Common.Database.Entities.Services.Server.DbServerInfo");

                    b.ToTable("server_info", (string)null);

                    b.HasDiscriminator().HasValue("Login");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccountWorldData", b =>
                {
                    b.HasOne("Edelstein.Common.Database.Entities.DbAccount", "Account")
                        .WithMany("AccountWorldData")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Session.DbSessionInfo", b =>
                {
                    b.HasOne("Edelstein.Common.Database.Entities.Services.Server.DbServerInfo", "Server")
                        .WithMany("Sessions")
                        .HasForeignKey("ServerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.DbAccount", b =>
                {
                    b.Navigation("AccountWorldData");
                });

            modelBuilder.Entity("Edelstein.Common.Database.Entities.Services.Server.DbServerInfo", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
