namespace Edelstein.Common.Gameplay.Packets;

public enum PacketRecvOperations : short
{
    DUMMY_CODE = 100,

    BEGIN_SOCKET = 101,
    SecurityPacket = 102,
    PermissionRequest = 103,
    LoginBasicInfo = 104,
    CheckLoginAuthInfo = 105,
    SelectWorld = 106,
    CheckSPWRequest = 107,
    CheckSPWExistRequest = 109,
    MigrateIn = 110,
    SelectCharacter = 111,
    SelectGoToStarPlanet = 112,
    SelectAccount = 113,
    WorldInfoRequest = 114,
    WorldInfoForShiningRequest = 115,
    CheckDuplicatedID = 116,
    LogoutWorld = 117,
    PermissionRequest_Fake = 118,
    CheckLoginAuthInfo_Fake = 119,
    CreateMapleAccount_Fake = 120,
    SelectAccount_Fake = 121,
    SelectWorld_Fake = 122,
    SelectCharacter_Fake = 123,
    CreateNewCharacter_Fake = 124,
    CreateNewCharacter = 125,
    CreateNewCharacterInCS = 126,
    CreateNewCharacter_PremiumAdventurer = 127,
    DeleteCharacter = 128,
    ReservedDeleteCharacterConfirm = 129,
    ReservedDeleteCharacterCancel = 130,
    RenameCharacter = 131,
    AliveAck_Fake = 132,
    ExceptionLog = 133,
    PrivateServerPacket = 134,
    ResetLoginStateOnCheckOTP = 135,
    ChangeSPWRequest = 136,
    CheckSPWRequest_Fake = 137,
    CheckOTPRequest = 138,
    CheckDeleteCharacterOTP = 139,
    CheckOTPForWebLaunchingRequest = 140,
    CreateSecurityHandle = 141,
    AlbaRequest = 142,
    UpdateCharacterCard = 143,
    CheckCenterAndGameAreConnected = 144,
    ResponseToCheckAliveAck_Fake = 145,
    CreateMapleAccount = 146,
    AliveAck = 147,
    ResponseToCheckAliveAck = 148,
    ClientDumpLog = 149,
    CrcErrorLog = 150,
    PerformanceInfoProvidedConsent = 151,
    CheckHotfix = 152,
    ClientExceptionInfo = 153,
    WvsSetUpStep = 154,
    WvsCrashCallback = 155,

    END_SOCKET = 0x9d
}
