<Project>
  
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <LangVersion>12.0</LangVersion>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(ContinuousIntegrationBuild)' == 'true'">true</RestoreLockedMode>
    
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  
  <PropertyGroup>
    <MinVerDefaultPreReleaseIdentifiers>preview</MinVerDefaultPreReleaseIdentifiers>
    <MinVerMinimumMajorMinor>1.0</MinVerMinimumMajorMinor>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="MinVer" PrivateAssets="All" />
  </ItemGroup>
  
</Project>