<Project>
  <PropertyGroup>
    <DotNetPackageVersion>9.0.0-preview.7.24405.7</DotNetPackageVersion>
    <DotNettyVersion>0.7.2012.2221</DotNettyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BinarySerializer" Version="8.6.4.1" />
    <PackageVersion Include="CommunityToolkit.HighPerformance" Version="8.2.2" />
    <PackageVersion Include="Duey.Abstractions" Version="2.0.0" />
    <PackageVersion Include="McMaster.NETCore.Plugins" Version="1.4.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="$(DotNetPackageVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="$(DotNetPackageVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="$(DotNetPackageVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="$(DotNetPackageVersion)" />
    <PackageVersion Include="SpanNetty.Buffers" Version="$(DotNettyVersion)" />
    <PackageVersion Include="SpanNetty.Codecs" Version="$(DotNettyVersion)" />
    <PackageVersion Include="SpanNetty.Common" Version="$(DotNettyVersion)" />
    <PackageVersion Include="SpanNetty.Handlers" Version="$(DotNettyVersion)" />
    <PackageVersion Include="SpanNetty.Transport" Version="$(DotNettyVersion)" />
    <PackageVersion Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <PackageVersion Include="MinVer" Version="5.0.0" />
  </ItemGroup>
</Project>