name: Publish (Latest)

on: [push]
  
jobs:

  setup:
    if: github.repository == 'Kaioru/Edelstein'

    name: Setup
    runs-on: ubuntu-latest

    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
    - uses: actions/checkout@v4
    - id: should_run
      continue-on-error: true
      name: Check for new commits
      if: ${{ github.event_name == 'schedule' }}
      run: test -z $(git rev-list --after="24 hours" ${{ github.sha }}) && echo "should_run=false" >> $GITHUB_OUTPUT

  versioning:
    needs: setup
    if: ${{ needs.setup.outputs.should_run != 'false' }}

    name: Versioning
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install Minver
      run: dotnet tool install --global minver-cli --version 4.3.0

    - name: Calculating version
      id: version
      run: echo "version=$(minver -m 1.0 -p preview -v e)" >> $GITHUB_OUTPUT

  publish:
    needs: [setup, versioning]
    if: ${{ needs.setup.outputs.should_run != 'false' }}

    name: Publish
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/publish.yml
      with:
        version: ${{ needs.versioning.outputs.version }}
        tag: latest
        prerelease: true
        draft: false