name: Publish (Nightly)

on: 
  schedule:
   - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
      name: Check latest commit
      outputs:
        should_run: ${{ steps.should_run.outputs.should_run }}
      steps:
        - uses: actions/checkout@v2
    - id: should_run
      continue-on-error: true
      name: Check new commits
      if: ${{ github.event_name == 'schedule' }}
      run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) &amp;&amp; echo "::set-output name=should_run::false"
      
  publish:
    needs: check
    if: ${{ needs.check.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Pack
      run: dotnet pack --configuration Release --version-suffix "nightly.$GITHUB_RUN_NUMBER" --output artifacts
    - name: Publish
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"