name: Publish (Dev Builds)

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Pack
      run: dotnet pack --configuration Release --version-suffix "dev.$GITHUB_RUN_NUMBER" --output artifacts
    - name: Publish
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"