name: Publish (Nightly)

on: 
  schedule:
  - cron: "0 0 * * *"
  
jobs:

  setup:
    if: github.repository == 'Kaioru/Edelstein'

    name: Setup
    runs-on: ubuntu-latest

    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
    - uses: actions/checkout@v4
    - id: should_run
      if: ${{ github.event_name == 'schedule' }}
      continue-on-error: true
      name: Check for new commits
      run: test -z $(git rev-list --after="24 hours" ${{ github.sha }}) && echo "should_run=false" >> $GITHUB_OUTPUT

  publish:
    needs: [setup]
    if: ${{ needs.setup.outputs.should_run != 'false' }}
    
    secrets: inherit
    uses: ./.github/workflows/publish.yaml
    with:
      tag: "nightly"
      prerelease: true
      draft: false